language: node_js
node_js:
  - 16
branches:
  only:
    - master
cache:
  npm: false
  directories:
    - "~/.pnpm-store"
before_install:
  - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@6
  - pnpm config set store-dir ~/.pnpm-store
jobs:
  include:
    - stage: Test
      install: pnpm install --force
      script:
        - pnpm test -- --projects ./packages/launcher --collectCoverage && pnpm codecov --filter launcher
    - stage: Build
      install: pnpm install --force
      script:
        - pnpm build --filter ./packages/launcher
